/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daltonic_show;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
 import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
/**
 *
 * @author nirfa
 */
public class crear_médico extends javax.swing.JFrame {

    /**
     * Creates new form crear_médico
     */
    public crear_médico() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("icon.png")).getImage();
        setIconImage(icon);
        this.setTitle("Crear Nuevo Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Nombre = new javax.swing.JTextField();
        apeido = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        contrasena = new javax.swing.JPasswordField();
        confirmacion = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 220, 30));
        getContentPane().add(apeido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 220, 30));

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 220, 30));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 220, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("*Cédula profesional:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("confirmar contraseña:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel8.setText("*Dato requerido para acceder al software");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        create.setText("crear usuario");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 110, 40));

        contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 240, 220, 30));
        getContentPane().add(confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daltonic_show/fondo-gris-tecnologia_1035-9343.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        String name = Nombre.getText();
        String surname = apeido.getText();
        String license = cedula.getText();
        String user = usuario.getText();
        String pass =  new String(contrasena.getPassword());
        String confirm =  new String(confirmacion.getPassword());
        
        int strlen1 = pass.length();
        int strlen2 = confirm.length();
        int tam = 0;
        boolean igual = true;
        boolean igual2 = true;
        if(strlen1 != strlen2){
            igual = false;
        }
        else{
            tam = strlen1;
            int i = 0;
            
            while(i<tam){
                char aux1 = pass.charAt(i);
                char aux2 = confirm.charAt(i);
                if(aux1 == aux2){
                    i++;
                }
                else{
                    igual2 = false;
                    break;
                }
            }
        }
        
        boolean cedu = true;
        if(igual == false  || igual2 == false){
            cedu = false;
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE, null);    
        }
        
        
        if (license.length() < 8){
                cedu = false;
                JOptionPane.showMessageDialog(null, "Cédula profesional no valida", "Error", JOptionPane.ERROR_MESSAGE, null);
            }
        
        if(igual == true){
            if(cedu == true){
                int resultado = 0; 
                Connection cnx = null;
                ResultSet rs = null;
                try {
                     Class.forName("com.mysql.jdbc.Driver");
                     cnx = DriverManager.getConnection("jdbc:mysql://localhost/bd_paciente?useTimezone=true&serverTimezone=UTC&useSSL=false", "jorgesolis12", "root2");
                     Statement st = cnx.createStatement();
                    String SSQL="SELECT * FROM oftalmologo WHERE usuario ="+ "'"+user+ "'";
                     rs = st.executeQuery(SSQL);
                     if(rs.next()){

                         resultado=1;

                     }
                     if(resultado == 1){
                           JOptionPane.showMessageDialog(null, "Usuario ya existente", "Error",JOptionPane.ERROR_MESSAGE);
                     }
                     else{
                        
                        PreparedStatement usuario = null;
                        usuario = cnx.prepareStatement("INSERT INTO oftalmologo VALUES (?,?,?,?,?)");
                        usuario.setString(1,license);
                        usuario.setString(2,name);
                        usuario.setString(3,surname);
                        usuario.setString(4,user);
                        usuario.setString(5,pass);
                        usuario.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Usuario Creado", "Información", JOptionPane.INFORMATION_MESSAGE, null);    

                     }
                     rs.close();
                 } catch (SQLException ex) {
                     Logger.getLogger(DS_main.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (ClassNotFoundException ex) {
                     Logger.getLogger(DS_main.class.getName()).log(Level.SEVERE, null, ex);
                 }
                         
            }
        }
    }//GEN-LAST:event_createActionPerformed

    private void contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crear_médico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crear_médico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crear_médico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crear_médico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crear_médico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField apeido;
    private javax.swing.JTextField cedula;
    private javax.swing.JPasswordField confirmacion;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
