/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daltonic_show;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author nirfa
 */
public class DS_main extends javax.swing.JFrame {

    /**
     * Creates new form DS_main
     */
    Connection cnx = null;
    ResultSet rs = null;
    s_paciente seleccion = new s_paciente();
    public DS_main() {
        initComponents(); 
        logut.setEnabled(false);
        diagnostico.setEnabled(false);
        selection.setEnabled(false);
        Welcome.setFont(new java.awt.Font("Tahoma", 1, 15));
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("Sesión no iniciada");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logut = new javax.swing.JButton();
        selection = new javax.swing.JButton();
        diagnostico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lg = new javax.swing.JButton();
        Welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        avis = new javax.swing.JMenuItem();
        directors = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logut.setText("Cerrar Sesión");
        logut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logutActionPerformed(evt);
            }
        });
        getContentPane().add(logut);
        logut.setBounds(610, 20, 110, 40);

        selection.setText("Seleccionar paciente");
        selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionActionPerformed(evt);
            }
        });
        getContentPane().add(selection);
        selection.setBounds(450, 230, 150, 40);

        diagnostico.setText("Diagnosticar Paciente");
        getContentPane().add(diagnostico);
        diagnostico.setBounds(450, 180, 150, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(651, 274, 0, 0);

        lg.setText("Iniciar sesión");
        lg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgActionPerformed(evt);
            }
        });
        getContentPane().add(lg);
        lg.setBounds(490, 20, 110, 40);
        getContentPane().add(Welcome);
        Welcome.setBounds(550, 70, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daltonic_show/11849.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 440, 380);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daltonic_show/preview.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 730, 450);

        jMenu1.setText("Opciones");

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        help.setText("Acerca de...");

        avis.setText("Aviso de privacidad");
        avis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avisActionPerformed(evt);
            }
        });
        help.add(avis);

        directors.setText("Directores y Desarrollo");
        directors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorsActionPerformed(evt);
            }
        });
        help.add(directors);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avisActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Todos la información recabada es con fines educativos al TT: 2019-A094 Prototipo de herramienta de apoyo al daltonismo\n, el cual se realiza en la Escuela Superior de cómputo del Instituto Politécnico Nacional,\n cualquier uso ajeno a este es responsabilidad de quien lo usa.\n Para mayor información por favor comunicarse directamente a la Escuela Superior de Cómputo.","Aviso de privacidad", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_avisActionPerformed

    private void directorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Realizado por:\n \tJorge Armando Solis Solis\n Directores:\n \t Rafael Norman Saucedo Delgado.\n \t Rosa Itzel Solis Solis","Aviso de privacidad",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_directorsActionPerformed

    private void lgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgActionPerformed
        // TODO add your handling code here:
       lg.setEnabled(false);

       int resultado = 0; 
       try {
            Class.forName("com.mysql.jdbc.Driver");
            cnx = DriverManager.getConnection("jdbc:mysql://localhost/bd_paciente?useTimezone=true&serverTimezone=UTC&useSSL=false", "jorgesolis12", "root2");
            Statement st = cnx.createStatement();
            
            String usuario = JOptionPane.showInputDialog(null,"Dame tu nombre de usuario");
            String contrasena = JOptionPane.showInputDialog(null,"Dame la contraseña");       
       
            String SSQL="SELECT * FROM oftalmologo WHERE usuario ="+ "'"+usuario+ "'"+"AND contrasena="+"'"+contrasena+"'";
            rs = st.executeQuery(SSQL);
            if(rs.next()){

            resultado=1;

            }
            
            if(resultado == 1){
                Welcome.setText("Bienvenido: Dr. "+rs.getString("nombre"));
                JOptionPane.showMessageDialog(null,"Sesión iniciada","Inicio de sesión",JOptionPane.INFORMATION_MESSAGE);
                logut.setEnabled(true);
                diagnostico.setEnabled(true);
                selection.setEnabled(true);
            }
            else{
                    JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "Por favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",JOptionPane.ERROR_MESSAGE);
                    lg.setEnabled(true);
 
            }
        } catch (SQLException ex) {
            Logger.getLogger(DS_main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DS_main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lgActionPerformed

    private void logutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logutActionPerformed
        try {
            // TODO add your handling code here:
            int option = JOptionPane.showConfirmDialog(
			null, 
			"¿Estás seguro de que quieres cerrar la aplicación?",
			"Confirmación de cierre", 
			JOptionPane.YES_NO_OPTION, 
			JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                rs.close();
                lg.setEnabled(true);
                JOptionPane.showMessageDialog(null,"Sesión Cerrada","Inicio de sesión",JOptionPane.INFORMATION_MESSAGE);
                Welcome.setText("Sesión no iniciada");
                logut.setEnabled(false);
                diagnostico.setEnabled(false);
                selection.setEnabled(false);
                seleccion.setVisible(false);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(DS_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(
			null, 
			"¿Estás seguro de que quieres cerrar la aplicación?",
			"Confirmación de cierre", 
			JOptionPane.YES_NO_OPTION, 
			JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
       
        
    }//GEN-LAST:event_exitActionPerformed

    private void selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionActionPerformed
        // TODO add your handling code here:
        boolean evento = false;
        seleccion = new s_paciente();
        seleccion.setVisible(true);
        


    }//GEN-LAST:event_selectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DS_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DS_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DS_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DS_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DS_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcome;
    private javax.swing.JMenuItem avis;
    private javax.swing.JButton diagnostico;
    private javax.swing.JMenuItem directors;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton lg;
    private javax.swing.JButton logut;
    private javax.swing.JButton selection;
    // End of variables declaration//GEN-END:variables
}
