/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package daltonic_show;
/**
 *
 * @author nirfa
 */
public class hoja_paciente extends javax.swing.JFrame {

    /**
     * Creates new form hoja_paciente
     */
    int id = 0;
    public hoja_paciente(int id_recv) {
        initComponents();
        id = id_recv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        fecha_nac = new javax.swing.JLabel();
        ingreso = new javax.swing.JLabel();
        ultima_cita = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        editar.setText("editar paciente");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(240, 350, 140, 50);

        jButton1.setText("Habilitar Gafas");
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 350, 150, 50);

        eliminar.setText("eliminar usuario");
        getContentPane().add(eliminar);
        eliminar.setBounds(420, 350, 140, 50);
        getContentPane().add(fecha_nac);
        fecha_nac.setBounds(320, 190, 300, 30);
        getContentPane().add(ingreso);
        ingreso.setBounds(290, 230, 250, 30);
        getContentPane().add(ultima_cita);
        ultima_cita.setBounds(320, 270, 250, 30);
        getContentPane().add(nombre);
        nombre.setBounds(210, 130, 330, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 170, 220, 60);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("FECHA DE INGRESO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 220, 210, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("FECHA DE ÚLTIMA CITA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 270, 240, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 100, 150, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daltonic_show/66539476-fondo-de-póquer-de-color-azul-claro-minimalista-con-textura-transparente-compuesta-de-símbolos-de-la-tarj.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1340, 894);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fecha_nac;
    private javax.swing.JLabel ingreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel ultima_cita;
    // End of variables declaration//GEN-END:variables
}
