/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daltonic_show;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author nirfa
 */
public class resultado extends javax.swing.JFrame {

    /**
     * Creates new form resultado
     */
    String rest;
    public resultado(String resultado) {
        
        initComponents();
        rest = resultado;
        resultado_text.setText(rest);
        resultado_text.setHorizontalAlignment(SwingConstants.CENTER);
        resultado_text.setVerticalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultado_text = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultado_text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(resultado_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 440, 90));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 80, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EL PACIENTE TIENE COMO RESULTADO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 390, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daltonic_show/purple-iphone-wallpaper-11.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "¿Considera el resultado correcto?");
        // 0=yes, 1=no, 2=cancel
        if(input == 0){
            JOptionPane.showMessageDialog (null, "Resultado guardado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(input == 1){
            String correcto = JOptionPane.showInputDialog("Escribe el resultado correcto");
            JOptionPane.showMessageDialog (null, "Resultado guardado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        this.setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ok;
    private javax.swing.JLabel resultado_text;
    // End of variables declaration//GEN-END:variables
}
